baseURL = "https://ronovar.github.io/bas.github.io/"
copyright = "Dr. Borivoje Jagodić"
enablerobotstxt = true
languagecode = "en-us"
paginate = 50
theme = ["paige"]
timezone = "America/Los_Angeles"
titlecasestyle = "Go"

[params]
copystart = "2016"
name = "OME Audio"
custom_css = ["css/custom.css"]

[languages.en]
title = "Paige"
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "pojacala"
name = "Pojačala"
url = "/amplifiers/"
weight = 20

[[languages.en.menu.main]]
identifier = "pretpojacala"
name = "Pretpojačala"
url = "/preamplifiers/"
weight = 30

[[languages.en.menu.main]]
identifier = "pomocni uredaji"
name = "Pomoćni Uređaji"
url = "/pomoćni uređaji/"
weight = 40

[[languages.en.menu.main]]
identifier = "customization"
name = "Customization"
url = "/customization/"
weight = 50

[[languages.en.menu.main]]
identifier = "authors"
name = "Authors"
url = "/authors/"
weight = 60

[[languages.en.menu.main]]
identifier = "series"
name = "Series"
url = "/series/"
weight = 70

[[languages.en.menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 80

[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 90

[[languages.en.menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 100

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[module]
[[module.imports]]
path = "../themes/paige"

[outputs]
home = ["atom", "html", "json", "rss"]
section = ["atom", "html", "rss"]
taxonomy = ["atom", "html", "rss"]
term = ["atom", "html", "rss"]

[params.authors.will-faught]
default = true
email = "kia_ora@ptt.yu"
name = "Dr. Borivoje Jagodić"
url = "https://ronovar.github.io/bas.github.io/"

[params.paige.git]
commit_url = "https://github.com/willfaught/paige/commit/%s"

[[params.paige.feed.atom.authors]]
email = "kia_ora@ptt.yu"
name = "Dr. Borivoje Jagodić"
url = "https://ronovar.github.io/bas.github.io/"

[params.paige.feed.rss]
managing_editor = "will.faught@example.com (Will Faught)"
web_master = "will.faught@example.com (Will Faught)"

[params.paige.file_link]
content = "Edit this page"
disable = true
url = "https://github.com/willfaught/paige/edit/master/exampleSite/content/%s"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"
