baseURL = "https://ronovar.github.io/bas.github.io/"
copyright = "© Dr Borivoje Jagodić"
enablerobotstxt = true
languagecode = "en-us"
paginate = 50
theme = ["hugo-theme-gallery"]
timezone = "America/Los_Angeles"
titlecasestyle = "Go"