baseURL = "https://ronovar.github.io/bas.github.io/"
copyright = "Dr. Borivoje Jagodić"
enablerobotstxt = true
languagecode = "sr"
paginate = 50
theme = ["paige", "hugo-theme-gallery"]
timezone = "America/Los_Angeles"
titlecasestyle = "Go"

[params]
copystart = "2016"
name = "OME Audio"
custom_css = ["css/custom.css"]

[languages.en]
title = "Paige"
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "pojačala"
name = "Pojačala"
url = "/pojačala/"
weight = 20

[[languages.en.menu.main]]
identifier = "pretpojačala"
name = "Pretpojačala"
url = "/pretpojačala/"
weight = 30

[[languages.en.menu.main]]
identifier = "pomoćni uređaji"
name = "Pomoćni Uređaji"
url = "/pomoćni uređaji/"
weight = 40

[[languages.en.menu.main]]
identifier = "test oprema"
name = "Test Oprema"
url = "/test oprema/"
weight = 50

[[languages.en.menu.main]]
identifier = "zvučnici"
name = "Zvučnici"
url = "/zvučnici/"
weight = 60

[[languages.en.menu.main]]
identifier = "tutorijali"
name = "Tutorijali"
url = "/tutorijali/"
weight = 70

[[languages.en.menu.main]]
identifier = "biografija"
name = "Biografija"
url = "/biografija/"
weight = 80

[[languages.en.menu.main]]
identifier = "tagovi"
name = "Tagovi"
url = "/tags/"
weight = 90

[[languages.en.menu.main]]
identifier = "galerija"
name = "Galerija"
url = "/galerija/"
weight = 100

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[module]
[[module.imports]]
path = "../themes/paige"

[[module.imports]]
path = "../themes/hugo-theme-gallery"

[outputs]
home = ["atom", "html", "json", "rss"]
section = ["atom", "html", "rss"]
taxonomy = ["atom", "html", "rss"]
term = ["atom", "html", "rss"]

[params.authors.will-faught]
default = true
email = "kia_ora@ptt.yu"
name = "Dr. Borivoje Jagodić"
url = "https://ronovar.github.io/bas.github.io/"

[params.paige.git]
commit_url = "https://github.com/willfaught/paige/commit/%s"

[[params.paige.feed.atom.authors]]
email = "kia_ora@ptt.yu"
name = "Dr. Borivoje Jagodić"
url = "https://ronovar.github.io/bas.github.io/"

[params.paige.feed.rss]
managing_editor = "will.faught@example.com (Will Faught)"
web_master = "will.faught@example.com (Will Faught)"

[params.paige.file_link]
content = "Edit this page"
disable = true
url = "https://github.com/willfaught/paige/edit/master/exampleSite/content/%s"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"
